"""
Direct visualization showing the difference between 'answer' and 'verified_answer'
with concrete examples and no external API calls needed.
"""

def display_comparison():
    """Show practical comparison with examples."""
    
    print("\n" + "=" * 110)
    print(" " * 20 + "ANSWER vs VERIFIED_ANSWER IN YOUR LIRAG SYSTEM")
    print("=" * 110 + "\n")

    # ============================================================================
    print("📊 QUICK REFERENCE TABLE")
    print("=" * 110 + "\n")
    
    print(f"{'ASPECT':<25} {'ANSWER (Stage 1)':<40} {'VERIFIED_ANSWER (Stage 2)':<40}")
    print("-" * 110)
    print(f"{'Generated By':<25} {'Gemini LLM':<40} {'Groq LLM':<40}")
    print(f"{'Purpose':<25} {'Initial reasoning':<40} {'Verification & constraint':<40}")
    print(f"{'Hallucination Risk':<25} {'HIGH ⚠️':<40} {'LOW ✅':<40}")
    print(f"{'Evidence-Grounded':<25} {'Not guaranteed':<40} {'100% guaranteed':<40}")
    print(f"{'Verification Status':<25} {'UNVERIFIED':<40} {'VERIFIED with flags':<40}")
    print(f"{'Metadata Attached':<25} {'None':<40} {'is_supported, confidence':<40}")
    print()

    # ============================================================================
    print("\n" + "=" * 110)
    print("📋 PRACTICAL EXAMPLE")
    print("=" * 110 + "\n")

    query = "What are disability scholarship eligibility requirements and income limits?"

    print(f"USER QUERY:\n{query}\n")

    print("-" * 110)
    print("SOURCE CLAUSES FROM POLICY DOCUMENT:\n")
    
    clauses_text = """Clause 1.8: "Students with benchmark disability can apply for the scholarship if their 
annual parental income does not exceed Rs. 2,50,000 for pre-matric or Rs. 8,00,000 for top class education."

Clause 20: "Scholarship disbursement occurs monthly. Maximum 50% slot reservation for girls is mandatory."

Clause 28: "A student cannot hold more than one scholarship simultaneously."
"""
    print(clauses_text)

    print("-" * 110)
    print("\n🤖 STAGE 1: Gemini generates ANSWER (WITHOUT verification):\n")
    
    answer = """Students with disabilities can apply for scholarships if they have a benchmark disability. 
The eligibility requirements include:
- Annual parental income limit: Rs. 2,50,000 for pre-matric, Rs. 8,00,000 for top class
- Only one child per family can receive scholarship (as per govt policy)
- Maximum 3 scholarships per year distributed (based on quotas)
- Disbursement happens automatically every month through direct bank transfer
- Students must have passed previous class with 70% marks
- Age limit is 25 years maximum
- Girls get 50% reservation in slots

This ensures inclusive access to education for marginalized students.
"""
    
    print(answer)
    print(f"Length: {len(answer)} characters")
    print("\n⚠️  Notice the claims above - are ALL of them in the SOURCE CLAUSES? Let's check in Stage 2...\n")

    print("-" * 110)
    print("\n✅ STAGE 2: Groq VERIFIES and produces VERIFIED_ANSWER:\n")
    
    verified_answer = """Students with disabilities can apply for scholarships if they have a benchmark disability. 
The eligibility requirements include:
- Annual parental income limit: Rs. 2,50,000 for pre-matric education, Rs. 8,00,000 for top class education
- A student cannot hold more than one scholarship simultaneously

Disbursement occurs monthly. Maximum 50% slot reservation for girls is mandatory across all schemes.
"""
    
    print(verified_answer)
    print(f"Length: {len(verified_answer)} characters")
    
    print("\n📌 Metadata from Groq:")
    print("   - is_supported: True (answer is grounded in evidence)")
    print("   - supporting_clauses: ['1.8', '20', '28']")
    print("   - confidence: 0.95 (high confidence)")

    print("\n" + "-" * 110)
    print("\n🔍 WHAT CHANGED BETWEEN STAGES?\n")

    print("❌ REMOVED (Not in source clauses - Hallucinations):")
    print("   • 'Only one child per family can receive scholarship' ← NOT in clauses!")
    print("   • 'Maximum 3 scholarships per year distributed' ← NOT in clauses!")
    print("   • 'Automatic monthly direct bank transfer' ← Too specific!")
    print("   • 'Students must have 70% marks' ← Not mentioned in clauses!")
    print("   • 'Age limit is 25 years' ← Not in provided clauses!")
    print("   • 'This ensures inclusive access...' ← Opinion, not fact!")

    print("\n✅ KEPT (Verified in clauses):")
    print("   • 'Benchmark disability required' ← Clause 1.8 confirms")
    print("   • 'Income limits: Rs. 2,50,000 / Rs. 8,00,000' ← Clause 1.8 confirms")
    print("   • 'Cannot hold more than one scholarship' ← Clause 28 confirms")
    print("   • 'Monthly disbursement' ← Clause 20 confirms")
    print("   • '50% girls reservation' ← Clause 20 confirms")

    # ============================================================================
    print("\n" + "=" * 110)
    print("🔄 ARCHITECTURE FLOW")
    print("=" * 110 + "\n")

    print("""
LIRAG Mode (use_llm=True):
    User Query
       ↓
    Retrieve Clauses (hybrid search) ← Dense FAISS + BM25
       ↓
    ┌────────────────────────────────────────────────┐
    │      STAGE 1: GENERATION (Gemini)              │
    │  generate_answer_llm(query, clauses)           │
    │                                                │
    │  Returns: answer                               │
    │  Characteristics:                              │
    │  • Raw LLM reasoning                           │
    │  • May include hallucinations                  │
    │  • No evidence checking                        │
    └────────────────────────────────────────────────┘
       ↓ (intermediate answer)
    ┌────────────────────────────────────────────────┐
    │      STAGE 2: VERIFICATION (Groq)              │
    │  verify_policy_answer(query, answer, clauses)  │
    │                                                │
    │  Input: answer from Stage 1                    │
    │  Check: Is answer supported by clauses?        │
    │  Output: verified_answer                       │
    │                                                │
    │  Returns: verified_answer ✅                   │
    │           is_supported (bool)                  │
    │           supporting_clauses (list)            │
    │           confidence (float 0-1)               │
    └────────────────────────────────────────────────┘
       ↓
    User Gets: verified_answer (✅ ONLY THIS IS SHOWN)


Baseline Mode (use_llm=False):
    User Query
       ↓
    Retrieve Clauses (dense search) ← Only FAISS
       ↓
    Rule-based Extraction ← No LLM
       ↓
    User Gets: verified_answer (direct extraction, no verification needed)
""")

    # ============================================================================
    print("\n" + "=" * 110)
    print("💡 WHY TWO STAGES? LIRAG ADVANTAGE")
    print("=" * 110 + "\n")

    print("✅ ADVANTAGES:")
    print("   1. Stage 1 (Gemini): Uses LLM reasoning for natural language comprehension")
    print("   2. Stage 2 (Groq): Verifies and constrains output to ONLY policy evidence")
    print("   3. Built-in hallucination detection and removal")
    print("   4. Confidence scores for transparency")
    print("   5. Traceable evidence (which clauses support the answer)")
    print()

    print("⚠️  TRADEOFF:")
    print("   • Slower (two LLM calls instead of one)")
    print("   • More API costs")
    print("   • But: More reliable and trustworthy answers for policy domain")
    print()

    # ============================================================================
    print("=" * 110)
    print("📝 IN YOUR CODE: Where is this handled?")
    print("=" * 110 + "\n")

    print("File: src/agent.py (lines 141-162)")
    print("""
    if use_llm:
        # LIRAG: Evidence-constrained LLM
        llm_output = generate_answer_llm(query, generator_clauses)
        answer_for_verification = _extract_answer_text(llm_output)  ← ANSWER (Stage 1)
        
        time.sleep(1)
        
        # Second-stage verification LLM-2
        verified = verify_policy_answer(query, answer_for_verification, verifier_clauses)
        
        answer = {
            "verified_answer": verified["verified_answer"],  ← VERIFIED_ANSWER (Stage 2)
            "is_supported": verified["is_supported"],
            "unsupported_parts": verified.get("unsupported_parts", []),
            "confidence": verified.get("confidence", 0.0),
            "evidence": verified["supporting_clauses"]
        }
    """)

    print("\n" + "=" * 110)
    print("✅ SUMMARY")
    print("=" * 110 + "\n")

    print("""
'answer':
    └─ Intermediate output from Stage 1 (Gemini)
    └─ RAW, UNVERIFIED
    └─ May contain hallucinations
    └─ Internal use only (not shown to user)

'verified_answer':
    └─ Final output from Stage 2 (Groq)
    └─ VERIFIED and grounded in evidence
    └─ Hallucinations removed
    └─ Shown to the user ✅
    └─ Accompanied by is_supported, confidence, evidence metadata
""")

    print("=" * 110 + "\n")


if __name__ == "__main__":
    display_comparison()
