import os
import json
import logging
import time
import re
from openai import OpenAI
from typing import List, Dict, Any
from dotenv import load_dotenv

load_dotenv()

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class PolicyVerifier:
    def __init__(self, model: str = "llama-3.3-70b-versatile"):
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise ValueError("GROQ_API_KEY not found in .env")
        self.client = OpenAI(api_key=api_key, base_url="https://api.groq.com/openai/v1")
        self.model = model
        self.max_retries = 2

    @staticmethod
    def _clean_text(text: str) -> str:
        return re.sub(r"\s+", " ", text or "").strip()

    @staticmethod
    def _truncate_text(text: str, max_chars: int) -> str:
        cleaned = PolicyVerifier._clean_text(text)
        if len(cleaned) <= max_chars:
            return cleaned
        return cleaned[:max_chars].rstrip() + "..."

    @staticmethod
    def _format_clauses(top_k_clauses: List[Dict[str, str]], max_clauses: int = 6, max_chars_per_clause: int = 600) -> str:
        parts = []
        for idx, clause in enumerate(top_k_clauses[:max_clauses], start=1):
            cid = clause.get("clause_id", "unknown")
            ctext = clause.get("text", "")
            safe_text = PolicyVerifier._truncate_text(ctext, max_chars_per_clause)
            parts.append(f"- Clause {idx} ({cid}): {safe_text}")
        return "\n\n".join(parts)

    def _build_prompt(self, user_query: str, generated_answer: str, clauses_text: str) -> str:
        return f"""You are a policy verification assistant. Only use the provided clauses. Do not use external knowledge.
Check if the answer is materially supported by the clauses.
Set is_supported=true when the main claims are supported by one or more clauses and there is no direct contradiction.
If supported, return the same answer (or a minimally cleaned version).
If not supported, rewrite the answer strictly based on the clauses.
If no information is found, return: 'Not supported by policy document.'

Input:
Query: {self._clean_text(user_query)}
Answer: {self._clean_text(generated_answer)}
Clauses:
{clauses_text}

Return ONLY JSON:
{{
  "verified_answer": "...",
  "is_supported": true/false,
    "supporting_clauses": ["..."],
    "unsupported_parts": ["..."],
    "confidence": 0.0
}}"""

    def _build_payload(self, user_query: str, generated_answer: str, top_k_clauses: List[Dict[str, str]]) -> str:
        clauses_text = self._format_clauses(
            top_k_clauses,
            max_clauses=min(6, len(top_k_clauses)),
            max_chars_per_clause=500,
        )
        safe_answer = self._truncate_text(generated_answer, 1100)
        return self._build_prompt(user_query, safe_answer, clauses_text)

    @staticmethod
    def _safe_json(value: Any) -> str:
        return json.dumps(value, ensure_ascii=True)

    def _build_second_llm_decision_prompt(
        self,
        query: str,
        retrieved_clauses: Any,
        retrieved_ids: List[str],
        answer: str,
        generated_ids: List[str],
    ) -> str:
        return f"""You are evaluating whether a second LLM-based verification step is necessary in a Retrieval-Augmented Generation (RAG) system.

You are given:
1. A user query
2. Retrieved clauses (with clause IDs)
3. Answer generated by the primary LLM
4. Clause IDs cited by the primary LLM

Your tasks:

1. Check Grounding:
- Is the answer fully supported by the retrieved clauses?
- Output: SUPPORTED or HALLUCINATED

2. Check Attribution:
- Are the cited clause IDs present in the retrieved clause IDs?
- Output: CORRECT or INCORRECT

3. Decision on Second LLM Necessity:
Based on the above:
- If answer is SUPPORTED AND attribution is CORRECT -> output: \"SECOND_LLM_NOT_REQUIRED\"
- Otherwise -> output: \"SECOND_LLM_REQUIRED\"

Return STRICTLY in JSON format:
{{
  \"hallucination\": \"SUPPORTED or HALLUCINATED\",
  \"attribution\": \"CORRECT or INCORRECT\",
  \"second_llm_decision\": \"SECOND_LLM_REQUIRED or SECOND_LLM_NOT_REQUIRED\"
}}

---

Query:
{self._clean_text(query)}

Retrieved Clauses:
{self._safe_json(retrieved_clauses)}

Retrieved Clause IDs:
{self._safe_json(retrieved_ids)}

Generated Answer:
{self._clean_text(answer)}

Cited Clause IDs:
{self._safe_json(generated_ids)}"""

    def verify_answer(
        self, 
        user_query: str, 
        generated_answer: str, 
        top_k_clauses: List[Dict[str, str]]
    ) -> Dict[str, Any]:
        """
        Verify if generated_answer is fully supported by clauses.
        Returns strict JSON format.
        """
        for attempt in range(1, self.max_retries + 1):
            prompt = self._build_payload(
                user_query,
                generated_answer,
                top_k_clauses,
            )

            try:
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.1,
                    response_format={"type": "json_object"}
                )
                result = json.loads(response.choices[0].message.content)
                
                # Validate required keys
                required = ["verified_answer", "is_supported", "supporting_clauses"]
                if all(k in result for k in required):
                    if "unsupported_parts" not in result:
                        result["unsupported_parts"] = []
                    if "confidence" not in result:
                        result["confidence"] = 0.0
                    logger.info(f"Verification successful. Supported: {result['is_supported']}")
                    return result
                else:
                    logger.warning(f"Missing keys in response (attempt {attempt})")
            except json.JSONDecodeError:
                logger.warning(f"JSON parse error (attempt {attempt})")
            except Exception as e:
                logger.error("Groq API verification error on attempt %s: %s", attempt, e)

            if attempt < self.max_retries:
                logger.info("Retrying verification in 1 second (attempt %s of %s)", attempt + 1, self.max_retries)
                time.sleep(1)

        # Fallback
        logger.error("Verification failed after retries")
        return {
            "verified_answer": "Verification failed. Not supported by policy document.",
            "is_supported": False,
            "supporting_clauses": [],
            "unsupported_parts": ["Verification step failed."],
            "confidence": 0.0
        }

    def evaluate_second_llm_necessity(
        self,
        query: str,
        retrieved_clauses: Any,
        retrieved_ids: List[str],
        answer: str,
        generated_ids: List[str],
    ) -> Dict[str, str]:
        """
        Evaluate grounding + attribution and decide if second LLM is needed.
        Returns strict JSON-compatible dict with exactly three fields.
        """
        normalized_retrieved_ids = {str(x).strip() for x in (retrieved_ids or []) if str(x).strip()}
        normalized_generated_ids = [str(x).strip() for x in (generated_ids or []) if str(x).strip()]
        deterministic_attribution = "CORRECT" if set(normalized_generated_ids).issubset(normalized_retrieved_ids) else "INCORRECT"

        prompt = self._build_second_llm_decision_prompt(
            query=query,
            retrieved_clauses=retrieved_clauses,
            retrieved_ids=sorted(normalized_retrieved_ids),
            answer=answer,
            generated_ids=normalized_generated_ids,
        )

        hallucination = "HALLUCINATED"
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0,
                response_format={"type": "json_object"},
            )
            model_result = json.loads(response.choices[0].message.content)
            raw_h = str(model_result.get("hallucination", "")).upper().strip()
            if raw_h in {"SUPPORTED", "HALLUCINATED"}:
                hallucination = raw_h
        except Exception as e:
            logger.warning("Second-LLM necessity evaluation failed, using conservative fallback: %s", e)

        second_llm_decision = "SECOND_LLM_NOT_REQUIRED" if (hallucination == "SUPPORTED" and deterministic_attribution == "CORRECT") else "SECOND_LLM_REQUIRED"

        return {
            "hallucination": hallucination,
            "attribution": deterministic_attribution,
            "second_llm_decision": second_llm_decision,
        }

# Required simple integration function
def verify_answer(user_query: str, generated_answer: str, top_clauses: List[Dict[str, str]]) -> Dict[str, Any]:
    verifier = PolicyVerifier()
    return verifier.verify_answer(user_query, generated_answer, top_clauses)

# Standalone function for pipeline integration
def verify_policy_answer(user_query: str, generated_answer: str, top_k_clauses: List[Dict[str, str]]) -> Dict[str, Any]:
    return verify_answer(user_query, generated_answer, top_k_clauses)


def evaluate_second_llm_necessity(
    query: str,
    retrieved_clauses: Any,
    retrieved_ids: List[str],
    answer: str,
    generated_ids: List[str],
) -> Dict[str, str]:
    verifier = PolicyVerifier()
    return verifier.evaluate_second_llm_necessity(
        query=query,
        retrieved_clauses=retrieved_clauses,
        retrieved_ids=retrieved_ids,
        answer=answer,
        generated_ids=generated_ids,
    )

if __name__ == "__main__":
    # Test
    clauses = [
        {"clause_id": "3.1", "text": "The First and Second Rank holders..."},
        {"clause_id": "4.1", "text": "The scholarship is available... Age limit 30 years."}
    ]
    result = verify_policy_answer(
        "What is the age limit?",
        "Age limit is 30 years for PG scholarships.",
        clauses
    )
    print(json.dumps(result, indent=2))

